AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

inherit_gem:
  accessiblerb: rules.yml

Metrics/BlockLength:
  AllowedPatterns:
    - describe
    - context
    - shared_examples

# This gem does meta-programming and calling `private` with an argument makes
# the code far more readable.
Style/AccessModifierDeclarations:
  Enabled: false
