module Inoculate
  VERSION: String

  module Errors
    class Error < StandardError
    end
    class InitializationRequiresBlock < Error
    end
  end

  class Architect
  end

  def self.initialize: () { (Architect) -> void } -> void
end
